"""Dynamic colony-noise synthesis and mixing (SPECS.md / ``noise-recipe`` skill).

Training pairs are synthesised on the fly: a clean isolated phee call is the
**target**; the same call (optionally pitch/time perturbed) mixed with a
synthetic colony-noise bed is the **input**. Perturbations are applied to the
call *before* it is split into target/input, so the pair stays time-aligned and
only the additive noise differs.

Noise-bed composition (energy-weighted, RMS-normalised components):
  * 40 % pink noise (1/f)          — ventilation / AC
  * 50 % synthetic babble          — 5–10 attenuated, shifted conspecific calls
  * 10 % transients                — 5–20 ms white-noise bursts (cage rattling)

Mixing: SNR ~ U(-5, +15) dB, temporal offset ~ U(0, 500) ms.
Perturbations: pitch ±5 %, time stretch ±10 %.

**Interpretation note** (flagged per the noise-recipe skill): with no prior
``augment.py`` to match, the percentages are read as the *mixing proportion of a
composite noise bed* — each component is normalised to unit RMS, then summed
with the weights above. Changing any constant here is a deviation from SPECS.md.

All RNG flows through a caller-supplied :class:`torch.Generator` so a run is
reproducible; ``dataset.py`` re-seeds per (epoch, index) for augmentation
diversity that still replays exactly.
"""

from __future__ import annotations

import math

import torch

from vocdenoiser.denoise.config import Config

EPS = 1e-10


def _rms(x: torch.Tensor) -> torch.Tensor:
    return torch.sqrt(torch.mean(x**2) + EPS)


def _normalise_rms(x: torch.Tensor) -> torch.Tensor:
    return x / _rms(x)


def _uniform(low: float, high: float, generator: torch.Generator) -> float:
    return float(torch.empty(1).uniform_(low, high, generator=generator).item())


def _randint(low: int, high: int, generator: torch.Generator) -> int:
    """Inclusive-low, inclusive-high integer in [low, high]."""
    return int(torch.randint(low, high + 1, (1,), generator=generator).item())


def pink_noise(n: int, generator: torch.Generator) -> torch.Tensor:
    """1/f (pink) noise of length ``n``, unit-RMS.

    Generated by shaping white Gaussian noise in the rFFT domain with a
    ``1/sqrt(f)`` amplitude envelope (so power ∝ 1/f).
    """
    white = torch.randn(n, generator=generator)
    spec = torch.fft.rfft(white)
    freqs = torch.arange(spec.shape[0], dtype=torch.float32)
    scale = 1.0 / torch.sqrt(torch.clamp(freqs, min=1.0))
    scale[0] = scale[1] if scale.numel() > 1 else 1.0  # tame the DC term
    pink = torch.fft.irfft(spec * scale, n=n)
    return _normalise_rms(pink)


def transient_burst(n: int, cfg: Config, generator: torch.Generator) -> torch.Tensor:
    """A few short white-noise bursts (5–20 ms) at random offsets, unit-RMS."""
    out = torch.zeros(n)
    sr = cfg.effective_sr
    count = _randint(*cfg.n_transients, generator)
    for _ in range(count):
        dur_ms = _uniform(cfg.transient_ms_min, cfg.transient_ms_max, generator)
        burst_len = max(1, int(round(dur_ms * 1e-3 * sr)))
        if burst_len >= n:
            burst_len = n
        start = _randint(0, n - burst_len, generator)
        out[start : start + burst_len] += torch.randn(burst_len, generator=generator)
    if _rms(out) <= EPS:  # degenerate (all bursts cancelled / empty)
        return out
    return _normalise_rms(out)


def _fit_length(x: torch.Tensor, n: int) -> torch.Tensor:
    """Crop or zero-pad a waveform to exactly ``n`` samples."""
    if x.numel() >= n:
        return x[:n]
    return torch.nn.functional.pad(x, (0, n - x.numel()))


def babble(
    n: int, call_pool: list[torch.Tensor], cfg: Config, generator: torch.Generator
) -> torch.Tensor:
    """Conspecific chatter: 5–10 attenuated, randomly time-shifted calls summed.

    ``call_pool`` is a list of clean call waveforms (already at ``effective_sr``).
    Each drawn call is attenuated by a random dB gain, offset by 0–``max_offset_ms``,
    and accumulated. Returns unit-RMS (or zeros if the pool is empty).
    """
    out = torch.zeros(n)
    if not call_pool:
        return out
    k = _randint(cfg.babble_min_calls, cfg.babble_max_calls, generator)
    max_off = int(round(cfg.max_offset_ms * 1e-3 * cfg.effective_sr))
    for _ in range(k):
        idx = _randint(0, len(call_pool) - 1, generator)
        call = _normalise_rms(call_pool[idx].float())
        gain = 10.0 ** (_uniform(*cfg.babble_atten_db, generator) / 20.0)
        offset = _randint(0, max_off, generator) if max_off > 0 else 0
        seg = _fit_length(call, n)
        if offset:
            seg = torch.roll(seg, shifts=offset)
        out += gain * seg
    if _rms(out) <= EPS:
        return out
    return _normalise_rms(out)


def noise_bed(
    n: int, call_pool: list[torch.Tensor], cfg: Config, generator: torch.Generator
) -> torch.Tensor:
    """Weighted composite colony-noise bed (unit-RMS), length ``n``."""
    bed = (
        cfg.weight_pink * pink_noise(n, generator)
        + cfg.weight_babble * babble(n, call_pool, cfg, generator)
        + cfg.weight_transient * transient_burst(n, cfg, generator)
    )
    if _rms(bed) <= EPS:
        return bed
    return _normalise_rms(bed)


def mix_at_snr(
    clean: torch.Tensor, noise: torch.Tensor, snr_db: float
) -> torch.Tensor:
    """Add ``noise`` to ``clean`` scaled so their ratio is ``snr_db`` dB."""
    target_noise_rms = _rms(clean) / (10.0 ** (snr_db / 20.0))
    return clean + noise * (target_noise_rms / _rms(noise))


def pitch_shift(wav: torch.Tensor, cfg: Config, generator: torch.Generator) -> torch.Tensor:
    """Pitch-shift by a random ±``pitch_pct`` %, via torchaudio's phase vocoder."""
    import torchaudio.functional as AF

    ratio = 1.0 + _uniform(-cfg.pitch_pct, cfg.pitch_pct, generator) / 100.0
    n_steps = 12.0 * math.log2(ratio)  # percent -> semitones
    shifted = AF.pitch_shift(wav.unsqueeze(0), cfg.effective_sr, n_steps)
    return shifted.squeeze(0)


def time_stretch(wav: torch.Tensor, cfg: Config, generator: torch.Generator) -> torch.Tensor:
    """Time-stretch by a random ±``stretch_pct`` % (phase vocoder), pitch preserved.

    ``rate > 1`` compresses in time, ``< 1`` lengthens; the caller re-fits the
    result to the fixed clip length, so the target (clean) and input (noisy) share
    the same stretched call and stay aligned.
    """
    import torchaudio.functional as AF

    rate = 1.0 + _uniform(-cfg.stretch_pct, cfg.stretch_pct, generator) / 100.0
    n_fft, hop = 512, 128
    window = torch.hann_window(n_fft)
    spec = torch.stft(wav, n_fft, hop, window=window, return_complex=True)
    freq = spec.shape[-2]
    phase_advance = torch.linspace(0, math.pi * hop, freq)[..., None]
    stretched = AF.phase_vocoder(spec.unsqueeze(0), rate, phase_advance).squeeze(0)
    out = torch.istft(stretched, n_fft, hop, window=window)
    return out
